################################################################################   
#
#  File Name		: CLI-CONSISTENT-CHECK.tcl
#
#  Description       	:
#         This file was executed by tclsh thru QTP. QTP will invoke tclsh to
#         execute this file to load TCL libraries, including UAL and CAL.
#         After loading library, it loads testcase to check CLI command for
#         each GUI testcase. 
#         We need this file because we have to run 'tclsh' in this folder.
#
#  Revision History 	:
#         Date         Programmer        Description
#        -----------------------------------------------------------------------
#        22-Aug-07     Scott             Created
#
################################################################################

set NTGR_SCRIPT_NAME   	"CLI-CONSISTENT-CHECK"
array set ntgr_logOptions {
	LOG_FLAG		163
	LOG_HOST      	""
	LOG_HOST_PATH	""
	LOG_USER_NAME 	""
	LOG_USER_PASSWD 	""
	LOG_FD		0
}


source common_env.tcl

Netgear_start_log

# The following sourced file was generated by QTP automatically for each testcase, 
# it only has one line in this file looks like: 
# source "C:/MANAGE_GUI_ROOT/TESTCASE/xx../yy../zz../abcd.tcl"
#
# It's just to source the TCL consistent check file's full path

source ../../TESTCASE/CLI-CONSISTENT-CHECK.tcl

Netgear_stop_log
