
#########################################################################################
#                                                                                       #
#                    THIS FILE WAS GENERATED BY VBSCRIPT DYNAMICALLY                    #
#                                                                                       #
#                            USED TO CALL TCL SHELL FROM QTP                            #
#                                                                                       #
#                        CRATED BY SCOTT ZHANG,       2008/03/31                        #
#                                                                                       #
#########################################################################################

## Transmited TCL variables from VBScript....

if { [ catch {

    set ConfigBy "CLI"

    set TftpSvr "192.158.110.3"

    set TftpSvrNet "192.158.110.255"

    set SftpSvr "192.158.110.3"

    set SftpUser "selva"

    set SftpPassword "selva"

    set ScpSvr "192.168.10.5"

    set ScpUser "selva"

    set ScpPassword "selva"

    set Tftp6Svr "2001:470:f8db:4000:20c:29ff:fe17:6555"

    set Sftp6Svr "2001:470:f8db:4000:20c:29ff:fe17:6555"

    set Sftp6User "root"

    set Sftp6Password "root123"

    set Scp6Svr "2001:470:f8db:4000:20c:29ff:fe17:6555"

    set Scp6User "root"

    set Scp6Password "root123"

    set LocalDir "C:\aaa"

    set SslRootFile "netgear_root.pem"

    set SslServerFile "netgear_server.pem"

    set SslDhWeakFile "netgear_dhweak.pem"

    set SslDhStrongFile "netgear_dhstrong.pem"

    set Ssh1RsaFile "netgear_ssh_host_key"

    set Ssh2RsaFile "netgear_ssh_host_rsa_key"

    set Ssh2DsaFile "netgear_ssh_host_dsa_key"

    set DUT "SW0"

    set SW1 "SW1"

    set SW2 "SW2"

    set SW3 "SW3"

    set TG "S1"

    set A00 "0/7"

    set A01 "0/1"

    set A02 "0/2"

    set A03 "0/3"

    set A09 "0/4"

    set A10 "0/5"

    set A11 "0/6"

    set A12 "0/8"

    set A13 "0/9"

    set A14 "0/10"

    set A15 "0/11"

    set A16 "0/12"

    set A17 "0/13"

    set A18 "0/14"

    set B00 "2/0/7"

    set B01 "2/0/4"

    set B02 "2/0/5"

    set B03 "2/0/6"

    set B04 "2/0/8"

    set B05 "2/0/9"

    set B06 "2/0/10"

    set B07 "2/0/11"

    set B08 "2/0/12"

    set B09 "2/0/1"

    set B10 "2/0/2"

    set B17 "2/0/13"

    set B18 "2/0/14"

    set C00 "1/0/7"

    set C01 "1/0/13"

    set C02 "1/0/15"

    set C03 "1/0/1"

    set C05 "1/0/8"

    set D00 "1/0/7"

    set D01 "1/0/14"

    set D02 "1/0/15"

    set D03 "1/0/8"

    set T01 "0 9 0"

    set SPD01 "1000"

    set T02 "0 9 1"

    set SPD02 "1000"

    set T03 "0 9 2"

    set SPD03 "1000"

    set T09 "0 9 3"

    set SPD09 "1000"

    set T10 "0 9 4"

    set SPD10 "1000"

    set T17 "0 9 5"

    set SPD17 "1000"

    set NTGR_OK_MSG "Restore TestBed Configuration is PASSED"

    set NTGR_NG_MSG "Restore TestBed Configuration is FAILED"

    set NTGR_SCRIPT_NAME VBSCRIPT-CALL-TCL-SHELL

    array set ntgr_logOptions {LOG_FLAG 163 LOG_HOST {} LOG_HOST_PATH {} LOG_USER_NAME {} LOG_USER_PASSWD {} LOG_FD 0}

    source common_env.tcl

    if { 0 == $argc } {

        Netgear_start_log

    } else {

        Netgear_start_log [lindex $argv 1]

    }

    Netgear_SyncFromConfigDUTXml

    source "C:/AUTOMATION/CONFIG/META-DATA/ProductParameterTable.tcl"

    source "C:/AUTOMATION/Functionality/00AutomationSupport/Restore TestBed Configuration/Restore Testbed.tcl"

    if { 0 == $argc } {

        Netgear_stop_log

    } else {

        Netgear_stop_log [lindex $argv 1]

    }

} errMsg ] } {

    source common_env.tcl

    Netgear_log_file TCL__RUNTIME__ERROR $errMsg

    Netgear_log_file $NTGR_SCRIPT_NAME.tcl {Resetting configuration to automation default}

    if { $ConfigBy == "CLI"} {

        foreach sw [string trim $NTGR_DUT_LIST] {

            set ipaddr [_get_switch_ip_addr $sw]

            _ntgrResetConfig2AutomationDefault $sw "tftp://$TftpSvr/$ipaddr.txt"

        }

    }

    if { 0 == $argc } {

        Netgear_stop_log

    } else {

        Netgear_stop_log [lindex $argv 1]

    }

}
