package businessrouter.webelements;
import static com.codeborne.selenide.Selenide.$;
import static com.codeborne.selenide.Selenide.$x;

import com.codeborne.selenide.SelenideElement;
public class BrIPSecVpnElements {


    public SelenideElement addbutton             = $("#ipsce_policy_1");
    public SelenideElement deletebutton          = $("#ipsce_policy_3");
    public SelenideElement selectall             = $x("//*[@id=\"ipsce_policy_3\"]/div/div/table/thead/tr/th[1]/span/div/label/span/input");
    public SelenideElement enableordisable       = $("#ipsec_policyStatuscb");
    public SelenideElement policyname            = $("#ipsec_policyname");
    public SelenideElement policymode            = $x("//div[@class='ant-select-selection__rendered']");
    public SelenideElement policymodenettonet    = $x("//li[text()='Net-to-Net']");
    public SelenideElement remotegateway         = $("#ipsec_policyremoteGateway");
    public SelenideElement remotesubnet1         = $("#ipsec_policyinputSubnet1");
    public SelenideElement remotesubnet2         = $("#ipsec_policyinputSubnet2");
    public SelenideElement remotesubnet3         = $("#ipsec_policyinputSubnet3");
    public SelenideElement remotesubnet4         = $("#ipsec_policyinputSubnet4");
    public SelenideElement remotemask1           = $("#ipsec_policyinputmask1");
    public SelenideElement remotemask2           = $("#ipsec_policyinputmask2");
    public SelenideElement remotemask3           = $("#ipsec_policyinputmask3");
    public SelenideElement remotemask4           = $("#ipsec_policyinputmask4");
    public SelenideElement localsubnet1         = $("#ipsec_policyinputlocalSubnet1");
    public SelenideElement localsubnet2         = $("#ipsec_policyinputlocalSubnet2");
    public SelenideElement localsubnet3         = $("#ipsec_policyinputlocalSubnet3");
    public SelenideElement localsubnet4         = $("#ipsec_policyinputlocalSubnet4");
    public SelenideElement localmask1           = $("#ipsec_policyinputlocalmask1");
    public SelenideElement localmask2           = $("#ipsec_policyinputlocalmask2");
    public SelenideElement localmask3           = $("#ipsec_policyinputlocalmask3");
    public SelenideElement localmask4           = $("#ipsec_policyinputlocalmask4");
    public SelenideElement presharedkey         =$("#ipsec_policypresharedkey");
    public SelenideElement ikev1         =$("#ipsec_ikev1");
    public SelenideElement ikev2         =$("#ipsec_ikev2");
    public SelenideElement advancedsettinglink         =$x("//span[@class ='span-text-bold']");
    public SelenideElement ph1proposal1eidt                = $x("/html/body/div[2]/div/div[2]/div/div[1]/form/div[12]/div[2]/div[2]/div/span/div/div/div");
    public SelenideElement ph1proposal11                = $x("(//li[text()='md5-3des-dh1'])[1]");
    public SelenideElement ph1proposal12                = $x("(//li[text()='md5-3des-dh2'])[1]");
    public SelenideElement ph1proposal13                = $x("(//li[text()='md5-3des-dh5'])[1]");
    public SelenideElement ph1proposal14                = $x("(//li[text()='md5-aes128-dh1'])[1]");
    public SelenideElement ph1proposal15                = $x("(//li[text()='md5-aes128-dh2'])[1]");
    public SelenideElement ph1proposal16                = $x("(//li[text()='md5-aes128-dh5'])[1]");
    public SelenideElement ph1proposal17                = $x("(//li[text()='md5-aes192-dh1'])[1]");
    public SelenideElement ph1proposal18                = $x("(//li[text()='md5-aes192-dh2'])[1]");
    public SelenideElement ph1proposal19                = $x("(//li[text()='md5-aes192-dh5'])[1]");
    public SelenideElement ph1proposal110                = $x("(//li[text()='md5-aes256-dh1'])[1]");
    public SelenideElement ph1proposal111                = $x("(//li[text()='md5-aes256-dh2'])[1]");
    public SelenideElement ph1proposal112                = $x("(//li[text()='md5-aes256-dh5'])[1]");
    public SelenideElement ph1proposal113                = $x("(//li[text()='sha1-3des-dh1'])[1]");
    public SelenideElement ph1proposal114                = $x("(//li[text()='sha1-3des-dh2'])[1]");
    public SelenideElement ph1proposal115                = $x("(//li[text()='sha1-3des-dh5'])[1]");
    public SelenideElement ph1proposal116                = $x("(//li[text()='sha1-aes128-dh1'])[1]");
    public SelenideElement ph1proposal117                = $x("(//li[text()='sha1-aes128-dh2'])[1]");
    public SelenideElement ph1proposal118                = $x("(//li[text()='sha1-aes128-dh5'])[1]");
    public SelenideElement ph1proposal119                = $x("(//li[text()='sha1-aes192-dh1'])[1]");
    public SelenideElement ph1proposal120                = $x("(//li[text()='sha1-aes192-dh2'])[1]");
    public SelenideElement ph1proposal121                = $x("(//li[text()='sha1-aes192-dh5'])[1]");
    public SelenideElement ph1proposal122                = $x("(//li[text()='sha1-aes256-dh1'])[1]");
    public SelenideElement ph1proposal123                = $x("(//li[text()='sha1-aes256-dh2'])[1]");
    public SelenideElement ph1proposal124                = $x("(//li[text()='sha1-aes256-dh5'])[1]");
    
    public SelenideElement ph1proposal2eidt                = $x("/html/body/div[2]/div/div[2]/div/div[1]/form/div[12]/div[3]/div[2]/div/span/div/div/div");
    public SelenideElement ph1proposal21                = $x("(//li[text()='md5-3des-dh1'])[2]");
    public SelenideElement ph1proposal22                = $x("(//li[text()='md5-3des-dh2'])[2]");
    public SelenideElement ph1proposal23                = $x("(//li[text()='md5-3des-dh5'])[2]");
    public SelenideElement ph1proposal24                = $x("(//li[text()='md5-aes128-dh1'])[2]");
    public SelenideElement ph1proposal25                = $x("(//li[text()='md5-aes128-dh2'])[2]");
    public SelenideElement ph1proposal26                = $x("(//li[text()='md5-aes128-dh5'])[2]");
    public SelenideElement ph1proposal27                = $x("(//li[text()='md5-aes192-dh1'])[2]");
    public SelenideElement ph1proposal28                = $x("(//li[text()='md5-aes192-dh2'])[2]");
    public SelenideElement ph1proposal29                = $x("(//li[text()='md5-aes192-dh5'])[2]");
    public SelenideElement ph1proposal210                = $x("(//li[text()='md5-aes256-dh1'])[2]");
    public SelenideElement ph1proposal211                = $x("(//li[text()='md5-aes256-dh2'])[2]");
    public SelenideElement ph1proposal212                = $x("(//li[text()='md5-aes256-dh5'])[2]");
    public SelenideElement ph1proposal213                = $x("(//li[text()='sha1-3des-dh1'])[2]");
    public SelenideElement ph1proposal214                = $x("(//li[text()='sha1-3des-dh2'])[2]");
    public SelenideElement ph1proposal215                = $x("(//li[text()='sha1-3des-dh5'])[2]");
    public SelenideElement ph1proposal216                = $x("(//li[text()='sha1-aes128-dh1'])[2]");
    public SelenideElement ph1proposal217                = $x("(//li[text()='sha1-aes128-dh2'])[2]");
    public SelenideElement ph1proposal218                = $x("(//li[text()='sha1-aes128-dh5'])[2]");
    public SelenideElement ph1proposal219                = $x("(//li[text()='sha1-aes192-dh1'])[2]");
    public SelenideElement ph1proposal220                = $x("(//li[text()='sha1-aes192-dh2'])[2]");
    public SelenideElement ph1proposal221                = $x("(//li[text()='sha1-aes192-dh5'])[2]");
    public SelenideElement ph1proposal222                = $x("(//li[text()='sha1-aes256-dh1'])[2]");
    public SelenideElement ph1proposal223                = $x("(//li[text()='sha1-aes256-dh2'])[2]");
    public SelenideElement ph1proposal224                = $x("(//li[text()='sha1-aes256-dh5'])[2]");
    
    public SelenideElement ph1proposal3eidt                = $x("/html/body/div[2]/div/div[2]/div/div[1]/form/div[12]/div[4]/div[2]/div/span/div/div/div");
    public SelenideElement ph1proposal31                = $x("(//li[text()='md5-3des-dh1'])[3]");
    public SelenideElement ph1proposal32                = $x("(//li[text()='md5-3des-dh2'])[3]");
    public SelenideElement ph1proposal33                = $x("(//li[text()='md5-3des-dh5'])[3]");
    public SelenideElement ph1proposal34                = $x("(//li[text()='md5-aes128-dh1'])[3]");
    public SelenideElement ph1proposal35                = $x("(//li[text()='md5-aes128-dh2'])[3]");
    public SelenideElement ph1proposal36                = $x("(//li[text()='md5-aes128-dh5'])[3]");
    public SelenideElement ph1proposal37                = $x("(//li[text()='md5-aes192-dh1'])[3]");
    public SelenideElement ph1proposal38                = $x("(//li[text()='md5-aes192-dh2'])[3]");
    public SelenideElement ph1proposal39                = $x("(//li[text()='md5-aes192-dh5'])[3]");
    public SelenideElement ph1proposal310                = $x("(//li[text()='md5-aes256-dh1'])[3]");
    public SelenideElement ph1proposal311                = $x("(//li[text()='md5-aes256-dh2'])[3]");
    public SelenideElement ph1proposal312                = $x("(//li[text()='md5-aes256-dh5'])[3]");
    public SelenideElement ph1proposal313                = $x("(//li[text()='sha1-3des-dh1'])[3]");
    public SelenideElement ph1proposal314                = $x("(//li[text()='sha1-3des-dh2'])[3]");
    public SelenideElement ph1proposal315                = $x("(//li[text()='sha1-3des-dh5'])[3]");
    public SelenideElement ph1proposal316                = $x("(//li[text()='sha1-aes128-dh1'])[3]");
    public SelenideElement ph1proposal317                = $x("(//li[text()='sha1-aes128-dh2'])[3]");
    public SelenideElement ph1proposal318                = $x("(//li[text()='sha1-aes128-dh5'])[3]");
    public SelenideElement ph1proposal319                = $x("(//li[text()='sha1-aes192-dh1'])[3]");
    public SelenideElement ph1proposal320                = $x("(//li[text()='sha1-aes192-dh2'])[3]");
    public SelenideElement ph1proposal321                = $x("(//li[text()='sha1-aes192-dh5'])[3]");
    public SelenideElement ph1proposal322                = $x("(//li[text()='sha1-aes256-dh1'])[3]");
    public SelenideElement ph1proposal323                = $x("(//li[text()='sha1-aes256-dh2'])[3]");
    public SelenideElement ph1proposal324                = $x("(//li[text()='sha1-aes256-dh5'])[3]");
    
    public SelenideElement ph1proposal4eidt                = $x("/html/body/div[2]/div/div[2]/div/div[1]/form/div[12]/div[5]/div[2]/div/span/div/div/div");
    public SelenideElement ph1proposal41                = $x("(//li[text()='md5-3des-dh1'])[4]");
    public SelenideElement ph1proposal42                = $x("(//li[text()='md5-3des-dh2'])[4]");
    public SelenideElement ph1proposal43                = $x("(//li[text()='md5-3des-dh5'])[4]");
    public SelenideElement ph1proposal44                = $x("(//li[text()='md5-aes128-dh1'])[4]");
    public SelenideElement ph1proposal45                = $x("(//li[text()='md5-aes128-dh2'])[4]");
    public SelenideElement ph1proposal46                = $x("(//li[text()='md5-aes128-dh5'])[4]");
    public SelenideElement ph1proposal47                = $x("(//li[text()='md5-aes192-dh1'])[4]");
    public SelenideElement ph1proposal48                = $x("(//li[text()='md5-aes192-dh2'])[4]");
    public SelenideElement ph1proposal49                = $x("(//li[text()='md5-aes192-dh5'])[4]");
    public SelenideElement ph1proposal410                = $x("(//li[text()='md5-aes256-dh1'])[4]");
    public SelenideElement ph1proposal411                = $x("(//li[text()='md5-aes256-dh2'])[4]");
    public SelenideElement ph1proposal412                = $x("(//li[text()='md5-aes256-dh5'])[4]");
    public SelenideElement ph1proposal413                = $x("(//li[text()='sha1-3des-dh1'])[4]");
    public SelenideElement ph1proposal414                = $x("(//li[text()='sha1-3des-dh2'])[4]");
    public SelenideElement ph1proposal415                = $x("(//li[text()='sha1-3des-dh5'])[4]");
    public SelenideElement ph1proposal416                = $x("(//li[text()='sha1-aes128-dh1'])[4]");
    public SelenideElement ph1proposal417                = $x("(//li[text()='sha1-aes128-dh2'])[4]");
    public SelenideElement ph1proposal418                = $x("(//li[text()='sha1-aes128-dh5'])[4]");
    public SelenideElement ph1proposal419                = $x("(//li[text()='sha1-aes192-dh1'])[4]");
    public SelenideElement ph1proposal420                = $x("(//li[text()='sha1-aes192-dh2'])[4]");
    public SelenideElement ph1proposal421                = $x("(//li[text()='sha1-aes192-dh5'])[4]");
    public SelenideElement ph1proposal422                = $x("(//li[text()='sha1-aes256-dh1'])[4]");
    public SelenideElement ph1proposal423                = $x("(//li[text()='sha1-aes256-dh2'])[4]");
    public SelenideElement ph1proposal424                = $x("(//li[text()='sha1-aes256-dh5'])[4]");
    
    public SelenideElement encryptionalgorithm2         =$x("(//div[@role = 'combobox'])[5]");
    public SelenideElement encryptionalgorithm2md5         =$x("(//li[text()='md5'])[2]");
    public SelenideElement encryptionalgorithm2sha1         =$x("(//li[text()='sha1'])[2]");
    public SelenideElement encryptionalgorithm2sha256         =$x("(//li[text()='sha256'])[2]");
    public SelenideElement encryptionalgorithm2sha384         =$x("(//li[text()='sha384'])[2]");
    public SelenideElement encryptionalgorithm2sha512         =$x("(//li[text()='sha512'])[2]");
    public SelenideElement integrityalgorithm2          =$x("(//div[@role = 'combobox'])[6]");
    public SelenideElement integrityalgorithm23des         =$x("(//li[text()='3des'])[2]");
    public SelenideElement integrityalgorithm2aes128         =$x("(//li[text()='aes128'])[2]");
    public SelenideElement integrityalgorithm2aes192         =$x("(//li[text()='aes192'])[2]");
    public SelenideElement integrityalgorithm2aes256         =$x("(//li[text()='aes256'])[2]");
    public SelenideElement pfskeygroup2         =$x("(//div[@role = 'combobox'])[7]");
    public SelenideElement pfskeygroup2no         =$x("(//li[text()='no'])[2]");
    public SelenideElement pfskeygroup2dh1         =$x("(//li[text()='dh1'])[2]");
    public SelenideElement pfskeygroup2dh2         =$x("(//li[text()='dh2'])[2]");
    public SelenideElement pfskeygroup2dh5         =$x("(//li[text()='dh5'])[2]");
    public SelenideElement pfskeygroup2dh14         =$x("(//li[text()='dh14'])[2]");
    public SelenideElement pfskeygroup2dh15         =$x("(//li[text()='dh15'])[2]");
    public SelenideElement pfskeygroup2dh16         =$x("(//li[text()='dh16'])[2]");
    public SelenideElement pfskeygroup2dh17         =$x("(//li[text()='dh17'])[2]");
    public SelenideElement pfskeygroup2dh18         =$x("(//li[text()='dh18'])[2]");
    public SelenideElement pfskeygroup2dh19         =$x("(//li[text()='dh19'])[2]");
    public SelenideElement pfskeygroup2dh20         =$x("(//li[text()='dh20'])[2]");
    public SelenideElement pfskeygroup2dh21         =$x("(//li[text()='dh21'])[2]");
    public SelenideElement pfskeygroup2dh22         =$x("(//li[text()='dh22'])[2]");
    public SelenideElement pfskeygroup2dh23         =$x("(//li[text()='dh23'])[2]");
    public SelenideElement pfskeygroup2dh24         =$x("(//li[text()='dh24'])[2]");
    
    public SelenideElement encryptionalgorithm3         =$x("(//div[@role = 'combobox'])[8]");
    public SelenideElement encryptionalgorithm3md5         =$x("(//li[text()='md5'])[3]");
    public SelenideElement encryptionalgorithm3sha1         =$x("(//li[text()='sha1'])[3]");
    public SelenideElement encryptionalgorithm3sha256         =$x("(//li[text()='sha256'])[3]");
    public SelenideElement encryptionalgorithm3sha384         =$x("(//li[text()='sha384'])[3]");
    public SelenideElement encryptionalgorithm3sha512         =$x("(//li[text()='sha512'])[3]");
    public SelenideElement integrityalgorithm3          =$x("(//div[@role = 'combobox'])[9]");
    public SelenideElement integrityalgorithm33des         =$x("(//li[text()='3des'])[3]");
    public SelenideElement integrityalgorithm3aes128         =$x("(//li[text()='aes128'])[3]");
    public SelenideElement integrityalgorithm3aes192         =$x("(//li[text()='aes192'])[3]");
    public SelenideElement integrityalgorithm3aes256         =$x("(//li[text()='aes256'])[3]");
    public SelenideElement pfskeygroup3         =$x("(//div[@role = 'combobox'])[10]");
    public SelenideElement pfskeygroup3no         =$x("(//li[text()='no'])[3]");
    public SelenideElement pfskeygroup3dh1         =$x("(//li[text()='dh1'])[3]");
    public SelenideElement pfskeygroup3dh2         =$x("(//li[text()='dh2'])[3]");
    public SelenideElement pfskeygroup3dh5         =$x("(//li[text()='dh5'])[3]");
    public SelenideElement pfskeygroup3dh14         =$x("(//li[text()='dh14'])[3]");
    public SelenideElement pfskeygroup3dh15         =$x("(//li[text()='dh15'])[3]");
    public SelenideElement pfskeygroup3dh16         =$x("(//li[text()='dh16'])[3]");
    public SelenideElement pfskeygroup3dh17         =$x("(//li[text()='dh17'])[3]");
    public SelenideElement pfskeygroup3dh18         =$x("(//li[text()='dh18'])[3]");
    public SelenideElement pfskeygroup3dh19         =$x("(//li[text()='dh19'])[3]");
    public SelenideElement pfskeygroup3dh20         =$x("(//li[text()='dh20'])[3]");
    public SelenideElement pfskeygroup3dh21         =$x("(//li[text()='dh21'])[3]");
    public SelenideElement pfskeygroup3dh22         =$x("(//li[text()='dh22'])[3]");
    public SelenideElement pfskeygroup3dh23         =$x("(//li[text()='dh23'])[3]");
    public SelenideElement pfskeygroup3dh24         =$x("(//li[text()='dh24'])[3]");
    
      
    public SelenideElement encryptionalgorithm4         =$x("(//div[@role = 'combobox'])[11]");
    public SelenideElement encryptionalgorithm4md5         =$x("(//li[text()='md5'])[4]");
    public SelenideElement encryptionalgorithm4sha1         =$x("(//li[text()='sha1'])[4]");
    public SelenideElement encryptionalgorithm4sha256         =$x("(//li[text()='sha256'])[4]");
    public SelenideElement encryptionalgorithm4sha384         =$x("(//li[text()='sha384'])[4]");
    public SelenideElement encryptionalgorithm4sha512         =$x("(//li[text()='sha512'])[4]");
    public SelenideElement integrityalgorithm4          =$x("(//div[@role = 'combobox'])[12]");
    public SelenideElement integrityalgorithm43des         =$x("(//li[text()='3des'])[4]");
    public SelenideElement integrityalgorithm4aes128         =$x("(//li[text()='aes128'])[4]");
    public SelenideElement integrityalgorithm4aes192         =$x("(//li[text()='aes192'])[4]");
    public SelenideElement integrityalgorithm4aes256         =$x("(//li[text()='aes256'])[4]");
    public SelenideElement pfskeygroup4         =$x("(//div[@role = 'combobox'])[13]");
    public SelenideElement pfskeygroup4no         =$x("(//li[text()='no'])[4]");
    public SelenideElement pfskeygroup4dh1         =$x("(//li[text()='dh1'])[4]");
    public SelenideElement pfskeygroup4dh2         =$x("(//li[text()='dh2'])[4]");
    public SelenideElement pfskeygroup4dh5         =$x("(//li[text()='dh5'])[4]");
    public SelenideElement pfskeygroup4dh14         =$x("(//li[text()='dh14'])[4]");
    public SelenideElement pfskeygroup4dh15         =$x("(//li[text()='dh15'])[4]");
    public SelenideElement pfskeygroup4dh16         =$x("(//li[text()='dh16'])[4]");
    public SelenideElement pfskeygroup4dh17         =$x("(//li[text()='dh17'])[4]");
    public SelenideElement pfskeygroup4dh18         =$x("(//li[text()='dh18'])[4]");
    public SelenideElement pfskeygroup4dh19         =$x("(//li[text()='dh19'])[4]");
    public SelenideElement pfskeygroup4dh20         =$x("(//li[text()='dh20'])[4]");
    public SelenideElement pfskeygroup4dh21         =$x("(//li[text()='dh21'])[4]");
    public SelenideElement pfskeygroup4dh22         =$x("(//li[text()='dh22'])[4]");
    public SelenideElement pfskeygroup4dh23         =$x("(//li[text()='dh23'])[4]");
    public SelenideElement pfskeygroup4dh24         =$x("(//li[text()='dh24'])[4]");
    
    public SelenideElement mainmode                =$("#ipsec_AdSetExchangeMode1");
    public SelenideElement aggressivemode          =$("#ipsec_AdSetExchangeMode2");
    public SelenideElement rsbothmode              =$("#ipsec_AdSetNegMode1");    
    public SelenideElement respondemode            =$("#ipsec_AdSetNegMode2");
    public SelenideElement salifetime            =$("#ipsec_AdSetSALifetime");
    public SelenideElement dpdyesorno            =$("#ipsec_pvAdSetDPD");
    public SelenideElement dpdinterval           =$("#ipsec_AdSetLocalId");
    public SelenideElement tunnelmode           =$("#ipsec_AdSetEncMode1");
    
    public SelenideElement ph2proposal1eidt                = $x("/html/body/div[2]/div/div[2]/div/div[1]/form/div[12]/div[13]/div[2]/div/span/div/div/div/div");
    public SelenideElement ph2proposal11                = $x("(//li[text()='esp-md5-3des'])[1]");
    public SelenideElement ph2proposal12                = $x("(//li[text()='esp-md5-aes128'])[1]");
    public SelenideElement ph2proposal13                = $x("(//li[text()='esp-md5-aes192'])[1]");
    public SelenideElement ph2proposal14                = $x("(//li[text()='esp-md5-aes256'])[1]");
    public SelenideElement ph2proposal15                = $x("(//li[text()='esp-sha1-3des'])[1]");
    public SelenideElement ph2proposal16                = $x("(//li[text()='esp-sha1-aes128'])[1]");
    public SelenideElement ph2proposal17                = $x("(//li[text()='esp-sha1-aes192'])[1]");
    public SelenideElement ph2proposal18                = $x("(//li[text()='esp-sha1-aes256'])[1]");
    
    public SelenideElement ph2proposal2eidt                = $x("/html/body/div[2]/div/div[2]/div/div[1]/form/div[12]/div[14]/div[2]/div/span/div/div/div");
    public SelenideElement ph2proposal21                = $x("(//li[text()='esp-md5-3des'])[2]");
    public SelenideElement ph2proposal22                = $x("(//li[text()='esp-md5-aes128'])[2]");
    public SelenideElement ph2proposal23                = $x("(//li[text()='esp-md5-aes192'])[2]");
    public SelenideElement ph2proposal24                = $x("(//li[text()='esp-md5-aes256'])[2]");
    public SelenideElement ph2proposal25                = $x("(//li[text()='esp-sha1-3des'])[2]");
    public SelenideElement ph2proposal26                = $x("(//li[text()='esp-sha1-aes128'])[2]");
    public SelenideElement ph2proposal27                = $x("(//li[text()='esp-sha1-aes192'])[2]");
    public SelenideElement ph2proposal28                = $x("(//li[text()='esp-sha1-aes256'])[2]");
    
    public SelenideElement ph2proposal3eidt                = $x("/html/body/div[2]/div/div[2]/div/div[1]/form/div[12]/div[15]/div[2]/div/span/div/div/div");
    public SelenideElement ph2proposal31                = $x("(//li[text()='esp-md5-3des'])[3]");
    public SelenideElement ph2proposal32                = $x("(//li[text()='esp-md5-aes128'])[3]");
    public SelenideElement ph2proposal33                = $x("(//li[text()='esp-md5-aes192'])[3]");
    public SelenideElement ph2proposal34                = $x("(//li[text()='esp-md5-aes256'])[3]");
    public SelenideElement ph2proposal35                = $x("(//li[text()='esp-sha1-3des'])[3]");
    public SelenideElement ph2proposal36                = $x("(//li[text()='esp-sha1-aes128'])[3]");
    public SelenideElement ph2proposal37                = $x("(//li[text()='esp-sha1-aes192'])[3]");
    public SelenideElement ph2proposal38                = $x("(//li[text()='esp-sha1-aes256'])[3]");
    
    public SelenideElement ph2proposal4eidt                = $x("/html/body/div[2]/div/div[2]/div/div[1]/form/div[12]/div[16]/div[2]/div/span/div/div/div");
    public SelenideElement ph2proposal41                = $x("(//li[text()='esp-md5-3des'])[4]");
    public SelenideElement ph2proposal42                = $x("(//li[text()='esp-md5-aes128'])[4]");
    public SelenideElement ph2proposal43                = $x("(//li[text()='esp-md5-aes192'])[4]");
    public SelenideElement ph2proposal44                = $x("(//li[text()='esp-md5-aes256'])[4]");
    public SelenideElement ph2proposal45                = $x("(//li[text()='esp-sha1-3des'])[4]");
    public SelenideElement ph2proposal46                = $x("(//li[text()='esp-sha1-aes128'])[4]");
    public SelenideElement ph2proposal47                = $x("(//li[text()='esp-sha1-aes192'])[4]");
    public SelenideElement ph2proposal48                = $x("(//li[text()='esp-sha1-aes256'])[4]");
    public SelenideElement ph2encryptionalgorithm  =$x("(//div[@role = 'combobox'])[14]");
    public SelenideElement ph2encryptionalgorithmesp  =$x("(//li[text()='esp'])[1]");
    public SelenideElement ph2authenticationalgorithm  =$x("(//div[@role = 'combobox'])[15]");
    public SelenideElement ph2authenticationalgorithmmd5  =$x("(//li[text()='md5'])[1]");
    public SelenideElement ph2authenticationalgorithmsha1 =$x("(//li[text()='sha1'])[1]");
    public SelenideElement ph2authenticationalgorithmsha256  =$x("(//li[text()='sha256'])[1]");
    public SelenideElement ph2authenticationalgorithmsha384 =$x("(//li[text()='sha384'])[1]");
    public SelenideElement ph2authenticationalgorithmsha512 =$x("(//li[text()='sha512'])[1]");
    
    public SelenideElement ph22authenticationalgorithm  =$x("(//div[@role = 'combobox'])[16]");
    public SelenideElement ph22authenticationalgorithm3des  =$x("(//li[text()='3des'])[1]");
    public SelenideElement ph22authenticationalgorithmaes128  =$x("(//li[text()='aes128'])[1]");
    public SelenideElement ph22authenticationalgorithmaes192  =$x("(//li[text()='aes192'])[1]"); 
    public SelenideElement ph22authenticationalgorithmaes256  =$x("(//li[text()='aes256'])[1]");
    
    
    public SelenideElement ph2encryptionalgorithm2  =$x("(//div[@role = 'combobox'])[17]");
    public SelenideElement ph2encryptionalgorithm2esp  =$x("(//li[text()='esp'])[2]");
    public SelenideElement ph2authenticationalgorithm2  =$x("(//div[@role = 'combobox'])[18]");
    public SelenideElement ph2authenticationalgorithm2md5  =$x("(//li[text()='md5'])[2]");
    public SelenideElement ph2authenticationalgorithm2sha1 =$x("(//li[text()='sha1'])[2]");
    public SelenideElement ph2authenticationalgorithm2sha256  =$x("(//li[text()='sha256'])[2]");
    public SelenideElement ph2authenticationalgorithm2sha384 =$x("(//li[text()='sha384'])[2]");
    public SelenideElement ph2authenticationalgorithm2sha512 =$x("(//li[text()='sha512'])[2]");
    
    public SelenideElement ph22authenticationalgorithm2  =$x("(//div[@role = 'combobox'])[19]");
    public SelenideElement ph22authenticationalgorithm23des  =$x("(//li[text()='3des'])[2]");
    public SelenideElement ph22authenticationalgorithm2aes128  =$x("(//li[text()='aes128'])[2]");
    public SelenideElement ph22authenticationalgorithm2aes192  =$x("(//li[text()='aes192'])[2]"); 
    public SelenideElement ph22authenticationalgorithm2aes256  =$x("(//li[text()='aes256'])[2]");
    
    
    public SelenideElement ph2encryptionalgorithm3  =$x("(//div[@role = 'combobox'])[20]");
    public SelenideElement ph2encryptionalgorithm3esp  =$x("(//li[text()='esp'])[3]");
    public SelenideElement ph2authenticationalgorithm3  =$x("(//div[@role = 'combobox'])[21]");
    public SelenideElement ph2authenticationalgorithm3md5  =$x("(//li[text()='md5'])[3]");
    public SelenideElement ph2authenticationalgorithm3sha1 =$x("(//li[text()='sha1'])[3]");
    public SelenideElement ph2authenticationalgorithm3sha256  =$x("(//li[text()='sha256'])[3]");
    public SelenideElement ph2authenticationalgorithm3sha384 =$x("(//li[text()='sha384'])[3]");
    public SelenideElement ph2authenticationalgorithm3sha512 =$x("(//li[text()='sha512'])[3]");
    
    public SelenideElement ph22authenticationalgorithm3  =$x("(//div[@role = 'combobox'])[22]");
    public SelenideElement ph22authenticationalgorithm33des  =$x("(//li[text()='3des'])[3]");
    public SelenideElement ph22authenticationalgorithm3aes128  =$x("(//li[text()='aes128'])[3]");
    public SelenideElement ph22authenticationalgorithm3aes192  =$x("(//li[text()='aes192'])[3]"); 
    public SelenideElement ph22authenticationalgorithm3aes256  =$x("(//li[text()='aes256'])[3]");
    
    public SelenideElement ph2encryptionalgorithm4  =$x("(//div[@role = 'combobox'])[23]");
    public SelenideElement ph2encryptionalgorithm4esp  =$x("(//li[text()='esp'])[4]");
    public SelenideElement ph2authenticationalgorithm4  =$x("(//div[@role = 'combobox'])[24]");
    public SelenideElement ph2authenticationalgorithm4md5  =$x("(//li[text()='md5'])[4]");
    public SelenideElement ph2authenticationalgorithm4sha1 =$x("(//li[text()='sha1'])[4]");
    public SelenideElement ph2authenticationalgorithm4sha256  =$x("(//li[text()='sha256'])[4]");
    public SelenideElement ph2authenticationalgorithm4sha384 =$x("(//li[text()='sha384'])[4]");
    public SelenideElement ph2authenticationalgorithm4sha512 =$x("(//li[text()='sha512'])[4]");
    
    public SelenideElement ph22authenticationalgorithm4  =$x("(//div[@role = 'combobox'])[25]");
    public SelenideElement ph22authenticationalgorithm43des  =$x("(//li[text()='3des'])[4]");
    public SelenideElement ph22authenticationalgorithm4aes128  =$x("(//li[text()='aes128'])[4]");
    public SelenideElement ph22authenticationalgorithm4aes192  =$x("(//li[text()='aes192'])[4]"); 
    public SelenideElement ph22authenticationalgorithm4aes256  =$x("(//li[text()='aes256'])[4]");
   
    public SelenideElement pfs  =$x("/html/body/div[2]/div/div[2]/div/div[1]/form/div[12]/div[17]/div[2]/div/span/div/div/div");
    public SelenideElement pfsno  =$x("//li[text()='no']");
    public SelenideElement pfsdh1  =$x("//li[text()='dh1']");
    public SelenideElement pfsdh2  =$x("//li[text()='dh2']");
    public SelenideElement pfsdh5  =$x("//li[text()='dh5']");
    public SelenideElement pfsdh14  =$x("//li[text()='dh14']");
    public SelenideElement pfsdh15  =$x("//li[text()='dh15']");
    public SelenideElement pfsdh16  =$x("//li[text()='dh16']");
    public SelenideElement pfsdh17  =$x("//li[text()='dh17']");
    public SelenideElement pfsdh18  =$x("//li[text()='dh18']");
    public SelenideElement pfsdh19  =$x("//li[text()='dh19']");
    public SelenideElement pfsdh20  =$x("//li[text()='dh20']");
    public SelenideElement pfsdh21  =$x("//li[text()='dh21']");
    public SelenideElement pfsdh22  =$x("//li[text()='dh22']");
    public SelenideElement pfsdh23  =$x("//li[text()='dh23']");
    public SelenideElement pfsdh24  =$x("//li[text()='dh24']");
    
    public SelenideElement ph2salifetime = $("#ipsec_AdSetSALifetime2");
    
    public SelenideElement applybutton  = $("#IPSec_PanelView_applybtn");
    public SelenideElement vnpstatus  = $x("//tr[@class = 'ant-table-row  ant-table-row-level-0'][1]/td[3]/img"); 
    public SelenideElement vpnpolicyokbutton  =$x("//*[@id=\"ipsce_policy_3_popDelete\"]/div/div/div[2]/button[2]");
    public SelenideElement vnpselectone  = $x("//*[@id=\"ipsce_policy_3\"]/div/div[2]/div/div/table/tbody/tr[1]/td[1]/span/label/span/input"); 
    public SelenideElement warningofsubnet = $x("//div[@class = 'ant-form-explain']");
    public SelenideElement vpneditbutton = $x("(//*[@id=\"ipsce_policy_1_1\"])[2]");
    public SelenideElement trafficrulesaction  = $x("(//div[@class='ant-select-selection__rendered'])[2]");
    public SelenideElement trafficrulesactionaccept  = $x("//li[text()='ACCEPT']");
    public SelenideElement trafficrulesactiondrop  = $x("//li[text()='DROP']");
}
