source ../LIB/NTGR/ntgr-cli-misc.tcl
source ../LIB/NTGR/ntgr-cli-login.tcl
source ../LIB/NTGR/ntgr-cli-parser.tcl
source ../LIB/NTGR/ntgr-cli-system-management.tcl
source ../LIB/NTGR/ntgr-cli-switching-port.tcl
source ../LIB/NTGR/ntgr-cli-switching-vlan.tcl
source ../LIB/NTGR/ntgr-cli-switching-lag.tcl
source ../LIB/NTGR/ntgr-cli-switching-stp.tcl
source ../LIB/NTGR/ntgr-cli-switching-mac-address-table.tcl
source ../LIB/NTGR/ntgr-cli-routing-ip.tcl
source ../LIB/NTGR/ntgr-cli-routing-vlan.tcl
source ../LIB/NTGR/ntgr-cli-routing-arp.tcl
source ../LIB/NTGR/ntgr-cli-routing-routing-table.tcl
source ../LIB/NTGR/ntgr-cli-qos-cos.tcl
source ../LIB/NTGR/ntgr-cli-maintenance.tcl
source ../LIB/NTGR/ntgr-cli-security-management.tcl
source ../LIB/NTGR/ntgr-cli-system-management-sntp.tcl
source ../LIB/NTGR/ntgr-cli-system-services-DAI.tcl
source ../LIB/NTGR/ntgr-cli-monitoring-logs.tcl
source ../LIB/NTGR/ntgr-cli-monitoring-sflow.tcl
source ../LIB/NTGR/ntgr-cli-security-privatevlan.tcl
source ../LIB/NTGR/ntgr-cli-routing-multicast-MLD.tcl
source ../LIB/NTGR/ntgr-cli-switching-iSCSI.tcl