package orbi.webelements;
import static com.codeborne.selenide.Selenide.$;
import static com.codeborne.selenide.Selenide.$x;

import com.codeborne.selenide.SelenideElement;
public class OrbiBasicGuestPortalElements {
    public SelenideElement enableguestportal   = $x("//*[@name= \"enable_guest_portal\"]");
    public SelenideElement enablessid   = $x("//*[@name= \"enable_ssid_broadcast\"]");
    public SelenideElement ssid  = $x("//*[@name= \"guest_ssid\"]");
    public SelenideElement wpa2psk  = $("#security_wpa2");
    public SelenideElement wpa2pskpassword   = $("#passphrase");
    public SelenideElement applybutton = $("#apply");
    //public SelenideElement none   = $x("/html/body/form/div[4]/table[7]/tbody/tr[2]/td/input");
    public SelenideElement none   = $x("//*[@id='local_wifi_auth']//input[@name='auth_type'][@value='none']");
    public SelenideElement authenticationnone   = $x("/html/body/form/div[4]/table[7]/tbody/tr[3]/td[1]/input");
    public SelenideElement inputauth            = $x("//input[@name='auth_type']");
    public SelenideElement authenticationauth   = $x("//*[@id='local_wifi_auth']//input[@name='auth_type'][@value='auth']");
    public SelenideElement authenticationpassword   = $x("//*[@name = \"auth_password\"]");
    public SelenideElement expiration   = $x("//*[@name = \"expire_time\"]");
    public SelenideElement termcondirtion = $("#txt_text");
    public SelenideElement logo = $("#logo_text");
    public SelenideElement defaulturltype = $x("//*[@name = \"use_url\"]");
    public SelenideElement customurl = $x("//*[@id=\"customize_sets\"]/table[4]/tbody/tr[3]/td/input[2]");
    public SelenideElement ssidboundwith = $("#enable_bandwidth_ssid");
    public SelenideElement telnetcheckbox = $x("//*[@id=\"main\"]/div[2]/form[1]/input[3]");
    public SelenideElement termcondirtionbrowse = $x("(//*[text()=\"Browse\"])[1]");
    public SelenideElement logobrowse = $x("(//*[text()=\"Browse\"])[2]");
    public SelenideElement clearbutton = $x("//*[@name=\"clear\"]");
    public SelenideElement previewbutton = $x("//*[@name=\"preview\"]");
    public SelenideElement yesbutton = $x("//*[@name=\"yes\"]");
    public SelenideElement nobutton = $x("//*[@name=\"no\"]");
    public SelenideElement clearportalcustomizationwarning = $x("/html/body/form/div[2]/table/tbody/tr[1]/td");
    public SelenideElement currenttermcordirtion  = $x("//*[@id=\"customize_sets\"]/table[2]/tbody/tr[2]/td/span");
    public SelenideElement currentlogo = $x("//*[@id=\"customize_sets\"]/table[3]/tbody/tr[1]/td/span");
    public SelenideElement logopicture = $("#logo");
    public SelenideElement termcordirtiontext = $("#user_text");
    public SelenideElement urlnone  =$x("(//*[@name=\"use_url\"])[1]");
    public SelenideElement urlnone2 =$x("(//*[@name=\"use_url\"])[2]");
    public SelenideElement url      =$x("//*[@id=\"customize_sets\"]/table[4]/tbody/tr[3]/td/input[2]");
    public SelenideElement vlanenable      =$x("//*[@id=\"basic_setting\"]/tbody/tr[5]/td[1]/input[2]");
    public SelenideElement vlanid      =$("#wlan_vlan_profile_list");
    public SelenideElement wirelessapplypercentage  = $("#apply_percentage");
}
